import assert from "node:assert/strict";
import test from "node:test";
import { liveDashboardHtml } from "../src/live-dashboard-html.mjs";

test("live dashboard makes unavailable-audit acknowledgement explicit in the approval card", () => {
  const html = liveDashboardHtml();

  assert.match(html, /当前为 SHADOW 模拟/);
  assert.match(html, /auditUnavailableAcknowledged/);
  assert.match(html, /审计数据不可用/);
  assert.match(html, /auditAcknowledgement\.checked = true/);
  assert.match(html, /requiresAuditAcknowledgement && !auditAcknowledgement\.checked/);
  assert.doesNotMatch(html, /if \(!window\.confirm\(warning\)\) return/);
  assert.doesNotMatch(html, /实时持仓，一眼看清/);
  assert.doesNotMatch(html, /Local only · Safety control dashboard/);
  assert.match(html, /class="top-stats"/);
  assert.match(html, /id="walletBalance"/);
  assert.match(html, /id="assetTrendChart"/);
  assert.match(html, /id="assetTrendSummary"/);
  assert.match(html, /function renderAssetTrend\(points\)/);
  assert.match(html, /new ResizeObserver\(drawAssetTrend\)/);
  assert.ok(html.indexOf('id="assetTrendChart"') < html.indexOf('id="approval"'));
  assert.match(html, /data\.walletBalance\?\.totalUsd/);
  assert.match(html, /data\.walletBalance\.assetCount \+ " 项资产/);
  assert.match(html, /id="realizedPnl"/);
  assert.match(html, /当前显示净盈亏/);
  assert.match(html, /预估净盈亏/);
  assert.match(html, /实际 P90/);
  assert.match(html, /固定估算/);
  assert.match(html, /已自动审批，等待重新报价与风控复核/);
  assert.match(html, /if \(request\.automaticallyApproved\)/);
  assert.match(html, /id="dailyLossRemaining"/);
  assert.match(html, /id="maxTrade"/);
  assert.match(html, /id="walletStatus"/);
  assert.match(html, /id="mode"><span class="dot"><\/span><span><\/span>/);
  assert.match(html, /function renderMode\(value\)/);
  assert.match(html, /normalized === "live" \? " green" : ""/);
  assert.match(html, /renderMode\(data\.mode\)/);
  assert.match(html, /function renderWalletStatus\(walletSession\)/);
  assert.match(html, /钱包 已连接/);
  assert.match(html, /钱包 已断开/);
  assert.match(html, /id="walletLogin"/);
  assert.match(html, /id="walletLoginStart"/);
  assert.match(html, /id="autoApprovalToggle"/);
  assert.match(html, /ENABLE_AUTO_APPROVAL/);
  assert.match(html, /打开 Binance 授权页面/);
  assert.match(html, /\/api\/wallet-login\/start/);
  assert.match(html, /\/api\/wallet-login\/status/);
  assert.doesNotMatch(html, /id="metrics"/);
  assert.match(html, /class="dashboard-grid"/);
  assert.match(html, /\.dashboard-grid \{ display: grid; grid-template-columns: repeat\(2, minmax\(0, 1fr\)\);/);
  assert.match(html, /\.signals-section \{ grid-column: 1 \/ -1; \}/);
  assert.match(html, /class="actions-section"/);
  assert.match(html, /\.actions-section \{ margin-top: 24px; \}/);
  assert.match(html, /id="strategyRisk"/);
  assert.match(html, /id="workflow"/);
  assert.ok(html.indexOf('class="actions-section"') > html.indexOf('id="workflow"'));
  assert.match(html, /function renderStrategyRisk\(data\)/);
  assert.match(html, /Shadow 风控/);
  assert.match(html, /仅观测，不改变下单/);
  assert.match(html, /shadowSuggestedTradeUsdt/);
  assert.match(html, /shadowTrendQualityDecision/);
  assert.match(html, /function renderWorkflow\(data\)/);
  assert.match(html, /href="\/strategies"/);
  assert.match(html, />策略<\/a>/);
  assert.doesNotMatch(html, /id="strategyComparison"/);
  assert.doesNotMatch(html, /function renderStrategies\(data\)/);
});

test("live dashboard provides an approval-first iPhone layout and compact signal table", () => {
  const html = liveDashboardHtml();

  assert.match(html, /env\(safe-area-inset-top\)/);
  assert.match(html, /href="\/favicon\.svg"/);
  assert.match(html, /env\(safe-area-inset-bottom\)/);
  assert.match(html, /class="signal-table-head"/);
  assert.match(html, />代码<\/span>/);
  assert.match(html, />方向<\/span>/);
  assert.match(html, />强度 \/ 15分钟<\/span>/);
  assert.match(html, />变化<\/span>/);
  assert.match(html, />拉取时间<\/span>/);
  assert.match(html, /signal\?\.dataFetchedAt/);
  assert.match(html, /const tradingViewSymbols = \{/);
  assert.match(html, /CRCL: "NYSE:CRCL"/);
  assert.match(html, /SPY: "AMEX:SPY"/);
  assert.match(html, /QQQ: "NASDAQ:QQQ"/);
  assert.match(html, /https:\/\/www\.tradingview\.com\/chart\/\?symbol=/);
  assert.match(html, /symbolLink\.target = "_blank"/);
  assert.match(html, /symbolLink\.rel = "noopener noreferrer"/);
  assert.match(html, /美股实时走势图 · TradingView/);
  assert.match(html, /id="signalToggle"/);
  assert.match(html, /id="signalContext"/);
  assert.match(html, /休市中 · 显示本地历史信号/);
  assert.match(html, /本地历史/);
  assert.match(html, /signal\.source/);
  assert.match(html, /signals\.classList\.toggle\("expanded"\)/);
  assert.match(html, /\.approval-button \{[^}]*min-height: 52px;/);
  assert.match(html, /@media \(max-width: 600px\)/);
  assert.match(html, /\.signal-table-head, \.signal \{ display: grid; grid-template-columns: 1\.05fr \.65fr 1\.15fr \.9fr \.85fr;/);
});
