import assert from "node:assert/strict";
import test from "node:test";
import { liveDashboardHtml } from "../src/live-dashboard-html.mjs";

test("live dashboard makes unavailable-audit acknowledgement explicit in the approval card", () => {
  const html = liveDashboardHtml();

  assert.match(html, /当前为 SHADOW 模拟/);
  assert.match(html, /auditUnavailableAcknowledged/);
  assert.match(html, /审计数据不可用/);
  assert.match(html, /auditAcknowledgement\.checked = true/);
  assert.match(html, /requiresAuditAcknowledgement && !auditAcknowledgement\.checked/);
  assert.doesNotMatch(html, /if \(!window\.confirm\(warning\)\) return/);
  assert.doesNotMatch(html, /实时持仓，一眼看清/);
  assert.doesNotMatch(html, /Local only · Safety control dashboard/);
  assert.match(html, /class="top-stats"/);
  assert.match(html, /grid-template-columns: repeat\(5, minmax\(0, 1fr\)\)/);
  assert.match(html, /id="marketIndexStatus"/);
  assert.match(html, /id="nasdaqIndex"/);
  assert.equal(html.match(/id="nasdaqIndex"/g)?.length, 1);
  assert.ok(html.indexOf('id="marketIndexStatus"') < html.indexOf('id="walletStatus"'));
  assert.doesNotMatch(html, /class="top-stat market-index"/);
  assert.match(html, /纳斯达克/);
  assert.match(html, /function renderMarketIndex\(marketIndex\)/);
  assert.match(html, /renderMarketIndex\(data\.marketIndex\)/);
  assert.match(html, /NASDAQ_OFFICIAL/);
  assert.match(html, /Nasdaq 官方延迟行情/);
  assert.match(html, /钱包总资产/);
  assert.match(html, /id="walletAvailableBalance"/);
  assert.match(html, /data\.walletBalance\?\.availableUsdt/);
  assert.match(html, /0x55d398326f99059fF775485246999027B3197955/);
  assert.match(html, /id="walletBalance"/);
  assert.match(html, /id="assetTrendChart"/);
  assert.match(html, /id="assetTrendSummary"/);
  assert.match(html, /function renderAssetTrend\(points\)/);
  assert.match(html, /new ResizeObserver\(drawAssetTrend\)/);
  assert.ok(html.indexOf('id="assetTrendChart"') < html.indexOf('id="approval"'));
  assert.match(html, /data\.walletBalance\?\.totalUsd/);
  assert.match(html, /data\.walletBalance\.assetCount \+ " 项资产/);
  assert.match(html, /id="realizedPnl"/);
  assert.match(html, /当前显示净盈亏/);
  assert.match(html, /预估净盈亏/);
  assert.match(html, /id="positionRefresh"/);
  assert.match(html, /positionRefresh\.addEventListener\("click"/);
  assert.match(html, /刷新中…/);
  assert.match(html, /position\.averageEntryPriceUsdt/);
  assert.match(html, /position\.executableMarketPriceUsdt/);
  assert.match(html, /position\.lastQuoteAt/);
  assert.match(html, /平均买入价/);
  assert.match(html, /市场实时价（可卖）/);
  assert.match(html, /盈利达到约/);
  assert.match(html, /普通卖出至少需要/);
  assert.doesNotMatch(html, /报价 MAE/);
  assert.doesNotMatch(html, /MFE/);
  assert.match(html, /const positions = Array\.isArray\(data\.positions\)/);
  assert.match(html, /positions\.forEach\(\(position\) =>/);
  assert.match(html, /实际 P90/);
  assert.match(html, /固定估算/);
  assert.match(html, /已自动审批，等待重新报价与风控复核/);
  assert.match(html, /if \(request\.automaticallyApproved\)/);
  assert.match(html, /id="dailyLossRemaining"/);
  assert.match(html, /id="maxTrade"/);
  assert.match(html, /id="walletStatus"/);
  assert.match(html, /id="mode"><span class="dot"><\/span><span><\/span>/);
  assert.match(html, /function renderMode\(value\)/);
  assert.match(html, /normalized === "live" \? " green" : ""/);
  assert.match(html, /renderMode\(data\.mode\)/);
  assert.match(html, /function renderWalletStatus\(walletSession\)/);
  assert.match(html, /钱包 已连接/);
  assert.match(html, /钱包 已断开/);
  assert.match(html, /id="walletLogin"/);
  assert.match(html, /id="walletLoginStart"/);
  assert.match(html, /id="autoApprovalToggle"/);
  assert.match(html, /ENABLE_AUTO_APPROVAL/);
  assert.match(html, /打开 Binance 授权页面/);
  assert.match(html, /\/api\/wallet-login\/start/);
  assert.match(html, /\/api\/wallet-login\/status/);
  assert.doesNotMatch(html, /id="metrics"/);
  assert.match(html, /class="dashboard-grid"/);
  assert.match(html, /\.dashboard-grid \{ display: grid; grid-template-columns: minmax\(0, 1\.35fr\) minmax\(340px, \.85fr\);/);
  assert.doesNotMatch(html, /\.positions-section \{ grid-column: 1 \/ -1; \}/);
  assert.match(html, /class="actions-section"/);
  assert.match(html, /\.actions-section \{ grid-column: 1 \/ -1; \}/);
  assert.match(html, /\.actions-section \.timeline \{ max-height: 560px;/);
  assert.match(html, /\.risk-section \{ margin-top: 24px; \}/);
  assert.match(html, /id="timelineDecisionFilter"/);
  assert.match(html, />决策判断 <span id="timelineDecisionCount">0<\/span><\/button>/);
  assert.match(html, /id="timelineTradeFilter"/);
  assert.match(html, />交易动作 <span id="timelineTradeCount">0<\/span><\/button>/);
  assert.match(html, /id="timelineSystemFilter"/);
  assert.match(html, />系统日志 <span id="timelineSystemCount">0<\/span><\/button>/);
  assert.match(html, /let timelineFilter = "decision"/);
  assert.match(html, /const decisionEvents = new Set\(\[/);
  assert.match(html, /const tradeEvents = new Set\(\[/);
  assert.match(html, /function actionCategory\(record\)/);
  assert.match(html, /function tradeActionSummary\(record\)/);
  assert.match(html, /交易审批：/);
  assert.match(html, /买入提交：/);
  assert.match(html, /卖出提交：/);
  assert.match(html, /持仓变化：/);
  assert.match(html, /details\.expectedProceedsUsdt \?\? details\.proceedsUsdt/);
  assert.match(html, /details\.gasUsdt \?\? details\.fallbackGasUsdt/);
  assert.match(html, /entry_decision: "入场判断"/);
  assert.match(html, /exit_decision: "退出判断"/);
  assert.match(html, /external_api_call: "外部接口调用"/);
  assert.match(html, /dynamic_exit_not_triggered: "未触发退出条件"/);
  assert.match(html, /STANDARD_ENTRY_CADENCE: "标准 15 分钟入场节奏"/);
  assert.match(html, /"wallet status": "钱包状态"/);
  assert.match(html, /skipped: "未执行"/);
  assert.match(html, /function actionSummary\(record\)/);
  assert.match(html, /el\("summary", "", "原始日志"\)/);
  assert.match(html, /\.timeline-filters \{ width: 100%; display: grid; grid-template-columns: repeat\(3, minmax\(0, 1fr\)\);/);
  assert.match(html, /\.event \{ grid-template-columns: 54px minmax\(0, 1fr\);/);
  assert.match(html, /id="strategyRisk"/);
  assert.match(html, /id="workflow"/);
  assert.ok(html.indexOf('id="position"') > html.indexOf('id="signals"'));
  assert.ok(html.indexOf('class="actions-section"') > html.indexOf('id="position"'));
  assert.ok(html.indexOf('id="strategyRisk"') > html.indexOf('class="actions-section"'));
  assert.match(html, /function renderStrategyRisk\(data\)/);
  assert.match(html, /Shadow 风控/);
  assert.match(html, /仅观测，不改变下单/);
  assert.match(html, /开放风险/);
  assert.match(html, /日亏损额度使用/);
  assert.match(html, /shadowSuggestedTradeUsdt/);
  assert.match(html, /shadowTrendQualityDecision/);
  assert.match(html, /function renderWorkflow\(data\)/);
  assert.match(html, /href="\/strategies"/);
  assert.match(html, />策略<\/a>/);
  assert.match(html, /href="\/reviews"/);
  assert.match(html, />复盘<\/a>/);
  assert.doesNotMatch(html, /id="strategyComparison"/);
  assert.doesNotMatch(html, /function renderStrategies\(data\)/);
});

test("live dashboard provides an approval-first iPhone layout and compact signal table", () => {
  const html = liveDashboardHtml();

  assert.match(html, /env\(safe-area-inset-top\)/);
  assert.match(html, /href="\/favicon\.svg"/);
  assert.match(html, /env\(safe-area-inset-bottom\)/);
  assert.match(html, /class="signal-table-head"/);
  assert.match(html, />代码<\/span>/);
  assert.match(html, />方向<\/span>/);
  assert.match(html, />强度 \/ 15分钟<\/span>/);
  assert.match(html, />变化<\/span>/);
  assert.match(html, />拉取时间<\/span>/);
  assert.match(html, /signal\?\.dataFetchedAt/);
  assert.match(html, /const tradingViewSymbols = \{/);
  assert.match(html, /CRCL: "NYSE:CRCL"/);
  assert.match(html, /SPY: "AMEX:SPY"/);
  assert.match(html, /QQQ: "NASDAQ:QQQ"/);
  assert.match(html, /https:\/\/www\.tradingview\.com\/chart\/\?symbol=/);
  assert.match(html, /symbolLink\.target = "_blank"/);
  assert.match(html, /symbolLink\.rel = "noopener noreferrer"/);
  assert.match(html, /美股实时走势图 · TradingView/);
  assert.match(html, /el\("span", "signal-identity"\)/);
  assert.match(html, /data\.stockMarketChanges\?\.\[symbol\]/);
  assert.match(html, /"今日 " \+ pct\(dailyChangePct\)/);
  assert.match(html, /Nasdaq 官方美股日涨跌/);
  assert.match(html, /id="signalToggle"/);
  assert.match(html, /id="signalContext"/);
  assert.match(html, /休市中 · 显示本地历史信号/);
  assert.match(html, /本地历史/);
  assert.match(html, /signal\.source/);
  assert.match(html, /signals\.classList\.toggle\("expanded"\)/);
  assert.match(html, /\.approval-button \{[^}]*min-height: 52px;/);
  assert.match(html, /@media \(max-width: 600px\)/);
  assert.match(html, /\.signal-table-head, \.signal \{ display: grid; grid-template-columns: 1\.05fr \.65fr 1\.15fr \.9fr \.85fr;/);
});

test("live dashboard embeds collapsed approvals in workflow stage four", () => {
  const html = liveDashboardHtml();

  assert.match(html, /class="top-asset-trend"/);
  assert.ok(html.indexOf('class="top-asset-trend"') < html.indexOf("</header>"));
  assert.doesNotMatch(html, /class="asset-trend-section"/);
  assert.match(html, /class="panel workflow-rail" id="workflowRail"/);
  assert.match(html, /id="workflow"[\s\S]*class="workflow-approval approval-section" id="approvalSection"/);
  assert.match(html, /阶段 4 · 逐笔确认/);
  assert.match(html, /id="approvalToggle"/);
  assert.match(html, /id="approvalSection"[^>]*data-expanded="false"/);
  assert.match(html, /aria-controls="approval"/);
  assert.match(html, /id="approvalCount">0<\/span>/);
  assert.match(html, /function setApprovalExpanded\(expanded\)/);
  assert.match(html, /approvalSection\.classList\.toggle\("has-approval", Boolean\(request\)\)/);
  assert.match(html, /const approvalStageCopy = data\.approvalRequest/);
  assert.match(html, /el\("small", "workflow-stage-status", approvalStageCopy\)/);
  assert.match(html, /approvalToggle\.addEventListener\("click"/);
  assert.ok(html.indexOf('id="signals"') < html.indexOf('id="position"'));
  assert.ok(html.indexOf('id="position"') < html.indexOf('class="actions-section"'));
  assert.ok(html.indexOf('class="actions-section"') < html.indexOf('id="strategyRisk"'));
});

test("live dashboard pulses only live executable strong signals and clears the style on refresh", () => {
  const html = liveDashboardHtml();

  assert.match(html, /@keyframes strong-signal-pulse/);
  assert.match(html, /\.signal\.strong-signal \{[^}]*animation: strong-signal-pulse/);
  assert.match(html, /const strongSignal = Boolean\(signalPassed && costsCovered && !historical && !marketClosed\)/);
  assert.match(html, /" strong-signal" : ""/);
  assert.match(html, /el\("small", "signal-strong", "强信号"\)/);
  assert.match(html, /@media \(prefers-reduced-motion: reduce\) \{[\s\S]*\.signal\.strong-signal \{ animation: none;/);
  assert.match(html, /root\.replaceChildren\(\)/);
});

test("live dashboard shows today's execution stages two through five on every signal row", () => {
  const html = liveDashboardHtml();

  assert.match(html, /function renderSignalDecisionStages\(symbol, stages\)/);
  assert.match(html, /\[2, 3, 4, 5\]\.forEach\(\(stage\) =>/);
  assert.match(html, /2: "风控"/);
  assert.match(html, /3: "创建订单"/);
  assert.match(html, /4: "逐笔确认"/);
  assert.match(html, /5: "执行"/);
  assert.match(html, /data\.signalDecisionStages\?\.\[symbol\]/);
  assert.match(html, /\.signal-journey \{ grid-column: 1 \/ -1;/);
  assert.match(html, /\.signal-stage\.failed \{[^}]*color: var\(--red\)/);
  assert.match(html, /\.signal-stage\.pending \{[^}]*color: var\(--gold\)/);
  assert.match(html, /\.signal-stage\.passed \{[^}]*color: var\(--green\)/);
  assert.match(html, /\.signal-stage\.idle \{/);
  assert.match(html, /\.signal-stage-tooltip \{/);
  assert.match(html, /\.signal-stage:hover \.signal-stage-tooltip, \.signal-stage:focus-visible \.signal-stage-tooltip/);
  assert.match(html, /tooltip\.setAttribute\("role", "tooltip"\)/);
  assert.match(html, /chip\.setAttribute\("aria-describedby", tooltipId\)/);
  assert.match(html, /chip\.tabIndex = 0/);
  assert.match(html, /"未通过原因："/);
  assert.match(html, /actionValue\("reason", decision\.reason\)/);
  assert.match(html, /decision\.count > 1 \? " · " \+ decision\.count \+ "次"/);
  assert.match(html, /renderSignalDecisionStages\(symbol, data\.signalDecisionStages\?\.\[symbol\]\)/);
  assert.match(html, /\.signal-journey \{ grid-template-columns: repeat\(2, minmax\(0, 1fr\)\);/);
});
